version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hakim
      POSTGRES_DB: pending-finance-db
    ports:
      - 5432:5432
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
